CREATE TABLE "film"
(
    "film_id"      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"         varchar NOT NULL,
    "description"  varchar NOT NULL,
    "release_date" date    NOT NULL,
    "duration"     int     NOT NULL,
    "rate"         int,
    "rating_id"    int     NOT NULL
);

CREATE TABLE "user"
(
    "user_id"  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email"    varchar UNIQUE NOT NULL,
    "login"    varchar        NOT NULL,
    "name"     varchar        NOT NULL,
    "birthday" date           NOT NULL
);

CREATE TABLE "like"
(
    "film_id" int NOT NULL,
    "user_id" int NOT NULL,
    CONSTRAINT "pk_like" PRIMARY KEY (
                                      "film_id", "user_id"
        )
);

CREATE TABLE "friend"
(
    "user_id"   int     NOT NULL,
    "friend_id" int     NOT NULL,
    "accepted"  boolean NOT NULL,
    CONSTRAINT "pk_friend" PRIMARY KEY (
                                        "user_id", "friend_id"
        )
);

CREATE TABLE "genre"
(
    "genre_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"     varchar UNIQUE NOT NULL
);

CREATE TABLE "rating"
(
    "rating_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"      varchar UNIQUE NOT NULL
);

CREATE TABLE "film_rating"
(
    "film_id"   int NOT NULL,
    "rating_id" int NOT NULL,
    CONSTRAINT "pk_film_rating" PRIMARY KEY (
                                             "film_id", "rating_id"
        )
);

CREATE TABLE "film_genre"
(
    "film_id"  int NOT NULL,
    "genre_id" int NOT NULL,
    CONSTRAINT "pk_film_genre" PRIMARY KEY (
                                            "film_id", "genre_id"
        )
);

ALTER TABLE "like"
    ADD CONSTRAINT "fk_like_film_id" FOREIGN KEY ("film_id")
        REFERENCES "film" ("film_id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "like"
    ADD CONSTRAINT "fk_like_user_id" FOREIGN KEY ("user_id")
        REFERENCES "user" ("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "friend"
    ADD CONSTRAINT "fk_friend_user_id" FOREIGN KEY ("user_id")
        REFERENCES "user" ("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "friend"
    ADD CONSTRAINT "fk_friend_friend_id" FOREIGN KEY ("friend_id")
        REFERENCES "user" ("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "film"
    ADD CONSTRAINT "fk_film_rating_id" FOREIGN KEY ("rating_id")
        REFERENCES "rating" ("rating_id");

ALTER TABLE "film_genre"
    ADD CONSTRAINT "fk_film_genre_film_id" FOREIGN KEY ("film_id")
        REFERENCES "film" ("film_id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "film_genre"
    ADD CONSTRAINT "fk_film_genre_genre_id" FOREIGN KEY ("genre_id")
        REFERENCES "genre" ("genre_id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "film_rating"
    ADD CONSTRAINT "fk_film_raiting_film_id" FOREIGN KEY ("film_id")
        REFERENCES "film" ("film_id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "film_rating"
    ADD CONSTRAINT "fk_film_raiting_rating_id" FOREIGN KEY ("rating_id")
        REFERENCES "rating" ("rating_id") ON DELETE CASCADE ON UPDATE CASCADE;

INSERT INTO "genre" ("name")
VALUES ('Комедия');
INSERT INTO "genre" ("name")
VALUES ('Драма');
INSERT INTO "genre" ("name")
VALUES ('Мультфильм');
INSERT INTO "genre" ("name")
VALUES ('Боевик');
INSERT INTO "genre" ("name")
VALUES ('Ужасы');
INSERT INTO "genre" ("name")
VALUES ('Триллер');
INSERT INTO "rating" ("name")
VALUES ('G');
INSERT INTO "rating" ("name")
VALUES ('PG');
INSERT INTO "rating" ("name")
VALUES ('PG-13');
INSERT INTO "rating" ("name")
VALUES ('R');
INSERT INTO "rating" ("name")
VALUES ('NC-17');

INSERT INTO "user" ("email", "login", "name", "birthday")
VALUES ('Jane@doe.com', 'JaneDoe', 'Jane Doe', '1970-01-01');

INSERT INTO "film" ("name", "description", "release_date", "duration", "rating_id")
VALUES ('Melancholia',
        'Two sisters find their already strained relationship challenged as a mysterious new planet threatens to collide with Earth.',
        '2011-05-18',
        135,
        4)