DROP TABLE "film" CASCADE;
DROP TABLE "user" CASCADE;
DROP TABLE "like" CASCADE;
DROP TABLE "friend" CASCADE;
DROP TABLE "genre" CASCADE;
DROP TABLE "rating" CASCADE;
DROP TABLE "film_genre" CASCADE;
DROP TABLE "film_rating" CASCADE;
